---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01"
      label: "System setup"
      solveButton: false
    - name: "module-02"
      label: "Building the first bootc container"
      solveButton: false
    - name: "module-03"
      label: "Deploying a virtual machine with bootc image"
      solveButton: false
    - name: "module-04"
      label: "Changing bootc hosts"
      solveButton: false
    - name: "module-05"
      label: "Rolling back a bootc host"
      solveButton: false
    - name: "module-06"
      label: "Adding security and compliance requirements"
      solveButton: false
    - name: "module-07"
      label: "Applying OpenSCAP policies"
      solveButton: false
    - name: "module-08"
      label: "Adding Troubleshooting tools"
      solveButton: false
    - name: "module-09"
      label: "Building a troubleshooting toolbox"
      solveButton: false
    - name: "module-10"
      label: "Dev mod troubleshoot"
      solveButton: false
    - name: "module-11"
      label: "Dev mod rebase"
      solveButton: false
    - name: "module-12"
      label: "Dev mod idiomatic"
      solveButton: false
    - name: "module-13"
      label: "Dev mod movin day"
      solveButton: false
    - name: "module-14"
      label: "Extra dev mod"
      solveButton: false

tabs:
  - name: "Build host"
    url: /wetty/ssh/root
  - name: "VM SSH session"
    url: /wetty_bootc_vm/ssh/root
  - name: "ISO SSH session"
    url: /wetty_iso_vm/ssh/root
  - name: "Security VM session"
    url: /wetty_security_vm/ssh/root
  - name: ">_ Image mode host"
    url: /wetty_imrhel/ssh/root
    modules:
      - module-10
      - module-11
      - module-12
      - module-13
      - module-14
