---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01"
      label: "Lab information"
      solveButton: false
    - name: "module-02"
      label: "Building the first bootc image"
      solveButton: false
    - name: "module-03"
      label: "Deploying a virtual machine with a bootc image"
      solveButton: false
    - name: "module-04"
      label: "Updating image mode hosts"
      solveButton: false
    - name: "module-05"
      label: "Rolling back an image mode host"
      solveButton: false
    - name: "module-06"
      label: "Adding security and compliance requirements"
      solveButton: false
    - name: "module-07"
      label: "Applying OpenSCAP policies"
      solveButton: false
    - name: "module-08"
      label: "Adding Troubleshooting tools"
      solveButton: false
    - name: "module-09"
      label: "Building a troubleshooting toolbox"
      solveButton: false
    - name: "module-10"
      label: "Troubleshooting an image mode deployment"
      solveButton: false
    - name: "module-11"
      label: "Using the standard baseline image"
      solveButton: false
    - name: "module-12"
      label: "Exploring container build practices"
      solveButton: false
    - name: "module-13"
      label: "Derived builds and updating the chain"
      solveButton: false
    - name: "module-drivers"
      label: "Platform targets"
      solveButton: false
    - name: "module-14"
      label: "Extra RH1 module: Scratch builds and rechunking"
      solveButton: false
    - name: "module-15"
      label: "Rechunk"
      solveButton: false

tabs:
  - name: "Build host terminal"
    url: /wetty/ssh/root
  - name: ">_ Rechunk test host"
    url: /wetty_imrhel/ssh/root
      - module-15
