---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01"
      label: "Lab information"
      solveButton: false
    - name: "module-02"
      label: "Building the first bootc image"
      solveButton: false
    - name: "module-03"
      label: "Deploying a virtual machine with a bootc image"
      solveButton: false
    - name: "module-04"
      label: "Updating image mode hosts"
      solveButton: false
    - name: "module-05"
      label: "Rolling back an image mode host"
      solveButton: false
    - name: "module-06"
      label: "Applying RHEL updates to the bootc base images"
      solveButton: false
    - name: "module-07"
      label: "Repurposing a bootc host"
      solveButton: false
    - name: "module-08"
      label: "Building an unattended install disk ISO"
      solveButton: false
    - name: "module-09"
      label: "Embedding credentials in an image"
      solveButton: false
    - name: "module-10"
      label: "Troubleshooting an image mode deployment"
      solveButton: false
    - name: "module-11"
      label: "Using the standard baseline image"
      solveButton: false
    - name: "module-12"
      label: "Exploring container build practices"
      solveButton: false
    - name: "module-13"
      label: "Derived builds and updating the chain"
      solveButton: false
    - name: "module-14"
      label: "Extra RH1 module: Scratch builds and rechunking"
      solveButton: false

tabs:
  - name: "Build host"
    url: /wetty/ssh/root
  - name: "VM SSH session"
    url: /wetty_bootc_vm/ssh/root
    modules:
      - module-2
      - module-3
      - module-4
      - module-5
  - name: "ISO SSH session"
    url: /wetty_iso_vm/ssh/root
    modules:
      - module-10
      - module-11
      - module-12
      - module-13
      - module-14
  - name: ">_ Image mode host"
    url: /wetty_imrhel/ssh/root
    modules:
      - module-10
      - module-11
      - module-12
      - module-13
      - module-14
